<script src="//ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script>window.jQuery || document.write('<script src="/assets/js/vendors/jquery.min.js"><\/script>');</script>
<script src="/assets/js/vendors.min.js"></script>
<script src="/assets/js/utils.js"></script>
<script src="/assets/js/slick.js" type="text/javascript" charset="utf-8"></script>
<script src="/assets/js/scripts.js"></script>