<footer id="l-footer" class="l-footer">
	<div class="l-footer__wrapper">
		 <div class="gooey-animations"></div>
         
         <ul>
          <li>
                <a class="social-button facebook" href="https://www.facebook.com/" target="_blank"><img src="/assets/images/icon-facebook.svg" class="fluid-image" alt=""></a>
           </li>
            <li>
                <a class="social-button youtube" href="https://www.youtube.com/" target="_blank"><img src="/assets/images/icon-youtube.svg" class="fluid-image" alt=""></a>
            </li>
            <li>
                <a class="social-button instagram" href="https://www.instagram.com/" target="_blank"><img src="/assets/images/icon-instagram.svg" class="fluid-image" alt=""></a>
            </li>
             <li>
                <a class="social-button tiktok" href="https://www.tiktok.com/" target="_blank"><img src="/assets/images/icon-tiktok.svg" class="fluid-image" alt=""></a>
            </li>
         </ul>
           
		<p class="txt-copyright"><small>&copy; ★★★, Ltd. All Rights Reserved.</small></p>
	</div>
</footer>
